#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User

easy_admin:
   entities:

     EventEntity:
       class: App\Entity\EventEntity
       list:
           fields:
               - title
               - type
               - description
               - startDate
               - endDate
               - city
               - address
               - { property: 'imageOne', type: 'image', base_path: '/images/event' }
               - { property: 'imageTwo', type: 'image', base_path: '/images/event' }
       show:
           fields:
               - title
               - type
               - description
               - startDate
               - endDate
               - place
               - city
               - address
               - adultPrice
               - teenagerPrice
               - childPrice
               - organizer
               - phone
               - uidEvent
               - { property: 'imageOne', type: 'image', base_path: '/images/event' }
               - { property: 'imageTwo', type: 'image', base_path: '/images/event' }
       form:
           fields:
               - { property: 'uidEvent', help: 'Name of event' }
               - title
               - type
               - description
               - startDate
               - endDate
               - place
               - city
               - address
               - adultPrice
               - teenagerPrice
               - childPrice
               - organizer
               - phone
               - { property: 'imageOneFile', type: 'vich_image' }
               - { property: 'imageTwoFile', type: 'vich_image' }