vich_uploader:
  db_driver: orm

  mappings:
      eventOne:
          uri_prefix: /images/event
          upload_destination: '%kernel.project_dir%/public/images/event'
      eventTwo:
          uri_prefix: /images/event
          upload_destination: '%kernel.project_dir%/public/images/event'

