#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

index:
  path: /
  defaults: { _controller: 'App\Controller\HomeController::index' }
discover:
  path: /discover
  defaults: { _controller: 'App\Controller\DiscoverController::index' }

